### ISSUE TITLE
require 'stn'

### ISSUE THREAD

**Issue by btekgit** [qassemoquab/stnbhwd#10]
I am sorry to ask you  in this way. But  I am very new to deep learning, torch, lua ... 
I am trying to run your code.  I do not have any nvidia card. So I replaced all 'cunn' with 'nn'. 
When I run the demo with >>qlua demo_mnist.lua
I got the following error. Which seems funny because I thought 'stn' is your library. If not where I can get it?

lua: demo_mnist_bt.lua:26: module 'stn' not found:
	no field package.preload['stn']
	no file '/home/btek/.luarocks/share/lua/5.1/stn.lua'
	no file '/home/btek/.luarocks/share/lua/5.1/stn/init.lua'
	no file '/home/btek/torch/install/share/lua/5.1/stn.lua'
	no file '/home/btek/torch/install/share/lua/5.1/stn/init.lua'
	no file './stn.lua'
	no file '/home/btek/torch/install/share/luajit-2.1.0-beta1/stn.lua'
	no file '/usr/local/share/lua/5.1/stn.lua'
	no file '/usr/local/share/lua/5.1/stn/init.lua'
	no file '/home/btek/torch/install/lib/stn.so'
	no file '/home/btek/.luarocks/lib/lua/5.1/stn.so'
	no file '/home/btek/torch/install/lib/lua/5.1/stn.so'
	no file './stn.so'
	no file '/usr/local/lib/lua/5.1/stn.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: at 0x7f5ba10899c0
	[C]: in function 'require'
	demo_mnist_bt.lua:26: in main chunk

**Comment by qassemoquab** [comment]
did you do "luarocks install stnbhwd-scm-1.rockspec"

**Comment by btekgit** [comment]
Thanks, I feared that I am asking something obvious. I am trying this now. But dependencies include "cutorch" (I assume I can not install this without nvidia card". So I erased dependencies to below.  Removed "cunn"s from the code as well. 
"
dependencies = {
   "torch >= 7.0",
   "nn >= 1.0",
}
"

But I still can not bypass CUDA dependency error as below. Any suggestions?

luarocks install stnbhwd-scm-1.rockspec
Using stnbhwd-scm-1.rockspec... switching to 'build' mode
Cloning into 'stnbhwd'...
remote: Counting objects: 24, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 24 (delta 0), reused 15 (delta 0), pack-reused 0
Receiving objects: 100% (24/24), 19.42 KiB | 0 bytes/s, done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/btek/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/btek/torch/install/lib/luarocks/rocks/stnbhwd/scm-1" && make

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/btek/torch/install
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Compiling with OpenMP support
CMake Error at /usr/share/cmake-2.8/Modules/FindCUDA.cmake:548 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:52 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_stnbhwd-scm-1-5492/stnbhwd/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.

**Comment by qassemoquab** [comment]
can you comment lines 52-78 in CMakeLists.txt ?

**Comment by btekgit** [comment]
Yes. I have done this already. But somehow I think it reads a precached version. Ignores, what I have commented.

**Comment by qassemoquab** [comment]
comment the lines, then do "luarocks make stnbhwd-scm-1.rockspec" ("make", not "install")

**Comment by btekgit** [comment]
Make solved it. Thanks very much for the help and also sharing the code!
