### ISSUE TITLE
transpose out of range at ...

### ISSUE THREAD

**Issue by kingofoz** [qassemoquab/stnbhwd#12]
Hi @qassemoquab 
I am trying the demo on my own dataset(color images) and I get a out of range error, looks tranet:add(nn.Transpose({2,3},{3,4})) is not suitable for me. Can you please tell me how to change it?

Thanks. 
-----------------------------------------------------------------------------------------------------------------------
qlua: /home/yingjun/torch/install/share/lua/5.1/nn/Container.lua:69: 
In 1 module of nn.Sequential:
In 1 module of nn.Sequential:
In 1 module of nn.ConcatTable:
In 2 module of nn.Sequential:
/home/yingjun/torch/install/share/lua/5.1/nn/Transpose.lua:14: bad argument #1 to 'transpose' (out of range at /tmp/luarocks_cutorch-scm-1-3039/cutorch/lib/THC/generic/THCTensor.c:406)
stack traceback:
	[C]: in function 'transpose'
	/home/yingjun/torch/install/share/lua/5.1/nn/Transpose.lua:14: in function </home/yingjun/torch/install/share/lua/5.1/nn/Transpose.lua:12>
	[C]: in function 'xpcall'
	/home/yingjun/torch/install/share/lua/5.1/nn/Container.lua:65: in function 'rethrowErrors'
	/home/yingjun/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/yingjun/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/home/yingjun/torch/install/share/lua/5.1/nn/Container.lua:65: in function 'rethrowErrors'
	...e/yingjun/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function <...e/yingjun/torch/install/share/lua/5.1/nn/ConcatTable.lua:9>
	[C]: in function 'xpcall'
	/home/yingjun/torch/install/share/lua/5.1/nn/Container.lua:65: in function 'rethrowErrors'
	/home/yingjun/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/yingjun/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/home/yingjun/torch/install/share/lua/5.1/nn/Container.lua:65: in function 'rethrowErrors'
	/home/yingjun/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	...un/torch/install/share/lua/5.1/nn/StochasticGradient.lua:35: in function 'train'
	scripts/train.lua:90: in main chunk

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
	[C]: at 0x7f8fbd75f970
	[C]: in function 'error'
	/home/yingjun/torch/install/share/lua/5.1/nn/Container.lua:69: in function 'rethrowErrors'
	/home/yingjun/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	...un/torch/install/share/lua/5.1/nn/StochasticGradient.lua:35: in function 'train'
	scripts/train.lua:90: in main chunk

**Comment by qassemoquab** [comment]
I don't know.

Some people managed to make it work with color images, so I guess the stn code runs fine.
https://github.com/moodstocks/gtsrb.torch
Maybe try to adapt their code to your stuff if the demo doesn't work out for you.

**Comment by qassemoquab** [comment]
(Also it's a bit hard to guess if you don't show any code...)

**Comment by kingofoz** [comment]
Thanks for the git you pointed, but I feel it is so complicated to a starter. Do you mind give me a mail box so I send my code to you?
