### ISSUE TITLE
gradientCorrection code

### ISSUE THREAD

**Issue by BestSonny** [qassemoquab/stnbhwd#13]
```
local gradientCorrection = torch.bmm(selectedGradParams:transpose(2,3), tParams)
      gradParams:narrow(3,1,2):narrow(2,1,2):add(1,gradientCorrection)
```

Does anyone knows the reason to compute these gradients? 

gradParams:narrow(3,1,2):narrow(2,1,2) seems has no relation with the translation gradient.

Can we delete these two lines?

**Comment by qassemoquab** [comment]
@albanD

**Comment by albanD** [comment]
@BestSonny  this update is for the case where you use both translation and another operation. This computation changes the `gradParams` following the composition rule such that the other transformations will compute the correct gradients when they use `gradParams` [here](https://github.com/qassemoquab/stnbhwd/blob/e706a98531fd3bd40a093189a72f7038fa56e77b/AffineTransformMatrixGenerator.lua#L181) and/or [here](https://github.com/qassemoquab/stnbhwd/blob/e706a98531fd3bd40a093189a72f7038fa56e77b/AffineTransformMatrixGenerator.lua#L199).
In the case where you use only the translation, yes this code is not useful. This is also true of [these](https://github.com/qassemoquab/stnbhwd/blob/e706a98531fd3bd40a093189a72f7038fa56e77b/AffineTransformMatrixGenerator.lua#L184-L187) lines if you do not use rotation. But keep in mind that these operations work on a very small matrix, and thus are very cheap.

**Comment by BestSonny** [comment]
@albanD  Great. I think I finally got your meaning.  Here is my understanding. All the translation output are actually not determined by just the two translation param. So, when in back-propagation phase, the gradParams:narrow(3,1,2):narrow(2,1,2) could be computed with its partial derivatives. Each of them should be updated with Grad_new = Grad_origin * ( 1 + Related_translation_param).

However, I think even in the case of only using translation. This code can also be useful and it is a must-do step.

**Comment by ys1045097987** [comment]
@BestSonny should be Grad_new=Grad_Origin+Grad_Origen_wrt_translation*Related_translation_param.
