### ISSUE TITLE
build error occurs when installing dependencies for Torch

### ISSUE THREAD

**Issue by WeitaoVan** [qassemoquab/stnbhwd#17]
I am trying to install these dependencies for Torch. When I type

`
luarocks install https://raw.githubusercontent.com/qassemoquab/stnbhwd/master/stnbhwd-scm-1.rockspec`

A fatal error occurs 

> [ 50%] Building NVCC (Device) object CMakeFiles/custn.dir//./custn_generated_init.cu.o
/tmp/luarocks_stnbhwd-scm-1-5260/stnbhwd/init.cu:2:17: fatal error: THC.h: No such file or directory
compilation terminated.
CMake Error at custn_generated_init.cu.o.cmake:206 (message):
  Error generating
  /tmp/luarocks_stnbhwd-scm-1-5260/stnbhwd/build/CMakeFiles/custn.dir//./custn_generated_init.cu.o

make[2]: *** [CMakeFiles/custn.dir/./custn_generated_init.cu.o] Error 1
make[1]: *** [CMakeFiles/custn.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

I have successfully installed Torch in ~/torch. Does anyone have any idea how I should install these dependencies for Torch? 

Thanks a lot!

**Comment by WeitaoVan** [comment]
Well, after I installed cutorch and cudnn, the problem was solved.
I thought that the cutorch and cudnn was OPTIONAL.

**Comment by agilebean** [comment]
For those who want to use CUDA 9 or above, you must clone the github repository and edit the CMakeLists.txt file in line 55:
Replace the flag from 'sm_20' to 'sm_30' like this:

    LIST(APPEND CUDA_NVCC_FLAGS "-arch=sm_30")

Then compile by

    luarocks make stnbhwd-scm-1.rockspec
