### ISSUE TITLE
Error while installing via luarocks

### ISSUE THREAD

**Issue by sidgan** [qassemoquab/stnbhwd#23]
`/tmp/luarocks_stnbhwd-scm-1-5189/stnbhwd/BilinearSamplerBHWD.cu(121): error: identifier "THCState_getCurrentStream" is undefined

/tmp/luarocks_stnbhwd-scm-1-5189/stnbhwd/BilinearSamplerBHWD.cu(309): error: identifier "THCState_getCurrentStream" is undefined

/tmp/luarocks_stnbhwd-scm-1-5189/stnbhwd/BilinearSamplerBHWD.cu(363): error: identifier "THCState_getCurrentStream" is undefined

3 errors detected in the compilation of "/tmp/tmpxft_000061c5_00000000-6_init.cpp1.ii".
CMake Error at custn_generated_init.cu.o.cmake:264 (message):
  Error generating file
  /tmp/luarocks_stnbhwd-scm-1-5189/stnbhwd/build/CMakeFiles/custn.dir//./custn_generated_init.cu.o

make[2]: *** [CMakeFiles/custn.dir/./custn_generated_init.cu.o] Error 1
make[1]: *** [CMakeFiles/custn.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.`

Any ideas as to why this occurs and how can it be fixed. I have all dependencies installed.

**Comment by soumith** [comment]
your cutorch is out of date.

luarocks install cutorch

**Comment by sidgan** [comment]
Thanks, I updated torch and then cutorch.
