### ISSUE TITLE
Error when installing 'luarocks install https://raw.githubusercontent.com/qassemoquab/stnbhwd/master/stnbhwd-scm-1.rockspec'

### ISSUE THREAD

**Issue by Montantes** [qassemoquab/stnbhwd#27]
Hello, I seem to be getting the error below, i looked in the previous closed errors and saw similar, but not quite the same. ive tried reinstalling the following. 

luarocks install torch
luarocks install nn
luarocks install image
luarocks install lua-cjson

Thanks in advance for your help.

-- Build files have been written to: /tmp/luarocks_stnbhwd-scm-1-ZFrwHp/stnbhwd/build
Scanning dependencies of target stn
[ 25%] Building C object CMakeFiles/stn.dir/init.c.o
[ 50%] Linking C shared module libstn.so
[ 50%] Built target stn
[ 75%] Building NVCC (Device) object CMakeFiles/custn.dir/custn_generated_init.cu.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at custn_generated_init.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_stnbhwd-scm-1-ZFrwHp/stnbhwd/build/CMakeFiles/custn.dir//./custn_generated_init.cu.o

CMakeFiles/custn.dir/build.make:63: recipe for target 'CMakeFiles/custn.dir/custn_generated_init.cu.o' failed
make[2]: *** [CMakeFiles/custn.dir/custn_generated_init.cu.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/custn.dir/all' failed
make[1]: *** [CMakeFiles/custn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by Montantes** [comment]
---SOLVED Using CUDA 8.0 instead of 7.5 (Ubuntu 16.04)----

**Comment by Shubhamcl** [comment]
Another solution would be adding the following line of code:
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES")

after line 40 in CMakeLists.txt

**Comment by yeboahjunior** [comment]
The issue may still persist with CUDA 8.0 in some cases. Exporting  your CUDA PATH:
export PATH=/usr/local/cuda-8.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/8.0/lib64:$LD_LIBRARY_PATH
and then sourcing bashrc should do the trick.

**Comment by kilmarnock** [comment]
CUDA 9.0 is also a problem, it complains about sm_20.  switching to CUDA 8.0 helps, says:

> nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).

**Comment by sabpap** [comment]
So does this work with CUDA 9 or switching to CUDA 8 is the only way?

**Comment by Montantes** [comment]
I haven't tried CUDA 9 yet. Have you tried some of the other solutions Shubhamcl mentioned?

Shubhamcl: Another solution would be adding the following line of code:
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES")

**Comment by tanisha-keshri** [comment]
i'm having cuda7 so i tried SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES")
but still the error is there what should i do ? . I am new in this area .
Thankyou for help .

**Comment by agilebean** [comment]
If you want to use CUDA 9, you must edit the CMakeLists.txt file in line 55:
Replace the flag from 'sm_20' to 'sm_30' like this:

      `LIST(APPEND CUDA_NVCC_FLAGS "-arch=sm_30")`

**Comment by nilinykh** [comment]
Problem surprisingly persists when working with CUDA 10.1, even after I change
`LIST(APPEND CUDA_NVCC_FLAGS "-arch=sm_20")`
to
`LIST(APPEND CUDA_NVCC_FLAGS "-arch=sm_30")`
