### ISSUE TITLE
bug in demo/distort_mnist.lua

### ISSUE THREAD

**Issue by zhfe99** [qassemoquab/stnbhwd#3]
[Line 38](https://github.com/qassemoquab/stnbhwd/blob/master/demo/distort_mnist.lua#L38)  is `res:select(1,i):copy(image.scale(s,32,32))`

But I guess it should be `res:select(1,i):copy(image.scale(distImg,32,32))`

**Comment by qassemoquab** [comment]
Nice catch, thanks ! 
Fixed in https://github.com/qassemoquab/stnbhwd/commit/34fa666b6684e70c9cd9b2a27cf8308c69d2646e.
