### ISSUE TITLE
why did you use baddbmm instead of bmm?

### ISSUE THREAD

**Issue by jnhwkim** [qassemoquab/stnbhwd#4]
In advance, thanks for this nice work, and sharing the code. 

In https://github.com/qassemoquab/stnbhwd/blob/master/AffineGridGeneratorBHWD.lua#L94, why did you use `torch.baddbmm`,

    self.gradInput:baddbmm(flattenedGradGrid:transpose(2,3), flattenedBatchGrid)

instead of 

    torch.bmm(self.gradInput, flattenedGradGrid:transpose(2,3), flattenedBatchGrid)

?

I saw your comment, `-- torch.baddbmm doesn't work on cudatensors for some reason`
and it triggers this question.

**Comment by qassemoquab** [comment]
I don't remember... 
I think it should be the same with bmm though.

**Comment by jnhwkim** [comment]
In my little test, it doesn't matter to switch to bmm. If I encounter any odds, I would let this issue thread know.
