### ISSUE TITLE
Isn't nn.AffineTransformMatrixGenerator a must-have module?

### ISSUE THREAD

**Issue by kingofoz** [qassemoquab/stnbhwd#9]
Hello,
I am looking at the demo: https://github.com/qassemoquab/stnbhwd/tree/master/demo
Seems you don't use nn.AffineTransformMatrixGenerator in https://github.com/qassemoquab/stnbhwd/blob/master/demo/spatial_transformer.lua
So there will no rotation, no scale, and no translation happen to images in training?

**Comment by qassemoquab** [comment]
That module puts constraints on the transform matrix.
If no transformation is specified, it generates a generic affine transformation (nbParams = 6), which should be the same as not using the module, as far as I understand.

**Comment by kingofoz** [comment]
Got it. Thank you.
